### ISSUE TITLE
zpMobile theme error when user is not logged in

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#1005]
When user is not logged in:

`Error: Maximum execution time of 90 seconds exceeded" in /data/web/virtuals/172972/virtual/www/zp-core/zp-extensions/class-video/getid3/getid3.php on line 1694 `

nPG 2.00.01.00.02

**Comment by sbillard** [comment]
I cannot reproduce this locally. Is there a specific video that triggers it? If so please attach it to the ticket. From the code, it would appear that the timeout is while trying to analyze the video for tags and such. Perhaps there is an issue with the particular video file.

**Comment by Mates-K1** [comment]
I get this error on main page. So... I dont know which video cause this. :(

**Comment by sbillard** [comment]
It does not happen if you are logged in? Maybe we can narrow things down by seeing what is showing on the main page when you are logged in. Or you can try refreshing metadata on the videos that might be showing.

Can you give me a link to your site?

**Comment by Mates-K1** [comment]
No, it does not happen when I am logged in.

https://skautskagalerie.cz

Sometimes there is no error but loading time is very long - about minute. And only in zpMobile theme and for not logged in users.

**Comment by sbillard** [comment]
I think this might also be a conflict created by jquerymobile. Maybe try with the very minimum of enabled plugins to see if the conflict can be isolated.

**Comment by sbillard** [comment]
I did find a way to slightly inhibit jquerymobile's mischief. I think it is an acceptable solution. Still have the show checkbox!

**Comment by sbillard** [comment]
closed the wrong one!

**Comment by sbillard** [comment]
Here is what I think is happening, please verify.

First, an  assumption. You have a large number of albums/images on the site that are not supposed to be visible to visitors unless they are logged in. 

zpmobile's index page will call getImageStatistic() to get eight images. I am presuming that the function is going through your whole list of images looking for eight it can show and not finding any. This process is instantiating each image and its album, so is pretty computationally intensive. It sometimes exceeds the max execution time, but always takes a long time.

At least when I visit the site there are no images shown. Since the site is intact visually I presume that there was no timeout, just no images found to show.

**Comment by sbillard** [comment]
I poked around on your site. Everything but the index page seems to be password protected. So I think the solution for your site would be to password protect the index page as well. 

I do not think there is any good solution for the situation where there are so many images to examine in order to find perhaps 8 to show. About the only thing that can be done is to prevent the timeout and perhaps cache the searches. That latter does not help the load time for the first visitor and is rather a complex business.

**Comment by sbillard** [comment]
I did get an idea. We can certainly limit the search to published albums if the viewer is not logged in. There still may not be any published images, but I think this will solve the issue in most normal sites.
