### ISSUE TITLE
mcrypt deprecated

### ISSUE THREAD

**Issue by JimBrown** [ZenPhoto20/netPhotoGraphics#898]
I'm in the process of updating my site to PHP 7. Using PHP 7.3.2 in my WAMP dev machine. Setup is complaining that the "mcrypt" extension should be enabled. Mcrypt is no longer available with PHP 7.3. Everything appears to be working (except one issue that is not related to mcrypt that I'm looking into...)

Thought I'd mention it here in case it is not yet on your "to do" list.

**Comment by sbillard** [comment]
Thanks. I had not yet migrated to php 7.3 

It is such a pain in the ... to upgrade WAMP versions. This time I even had to change the virtual host domain because it would not let me use wamp.dev (or any .dev for that matter.)

Still have to recreate my SSL certificates, but at least the test sites are running.

**Comment by JimBrown** [comment]
I hear you. Took me a couple of days to get Apache 2.4 and PHP 7.3 up and running (that's what my host is now using.)

I had to switch to .test from .dev a while ago. You can blame Google for that.

**Comment by sbillard** [comment]
Well, It only took me a half day to move to Wampserver 3.1.7! Most of that time was getting the SSL to work. for some reason the ssl modules were not enabled in the off the shelf 3.1.7. I am assuming they were enabled in th 3.0.6 version since I do not remember having to figure out they were not enabled. The rest was the hoop jumping to get everyone to accept my self-signed certificate.

But all is well now. I've not seen any PHP issues. Look forward to hearing if you do.
