### ISSUE TITLE
Enabling GDPR plugin completely disable site

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#924]
Just enable GDPR plugin... and it completely disable gallery site.

**Comment by sbillard** [comment]
What actually happened?  

Anyway, you can temporarily delete the plugin to get things going again.

**Comment by Mates-K1** [comment]
When plugin is enable, site is unavailable for non logged users.

For me, logged as admin, all works fine - I can access to gallery and to admin area too.

**Comment by Mates-K1** [comment]
I have reason...
If there is bad URL in plugin setting, site is unavailable.
![obrazek](https://user-images.githubusercontent.com/7648991/54150711-69c73b80-4439-11e9-8518-a407bcb4f5df.png)

**Comment by sbillard** [comment]
I don't think there is anything that should be done on that. The same issue would exist of there were a PHP error on the page, etc.

**Comment by Mates-K1** [comment]
I think it is a little bit "strictly" to non logged users when admin write bad URL and it shut down whole gallery for them.

I would expect only a bad link under the form in that case... :/

**Comment by sbillard** [comment]
I do not agree. If you enable the GDPR required plugin you are saying that visitors cannot view your site until they agree to the terms provided. Since you have an error in the link, they cannot agree to the terms, thus they cannot view the site.

**Comment by Mates-K1** [comment]
I wrote long post and in the end I realized that we each other are probably talking about something else. So deleted it and....

In general:
You - "you must confirm that you are over 18 years old"
Me - "GDPR = consent to the processing of personal data"

I think the GDPR does not have much to do with confirming that I am 18 years old. To make this not confusing, I would suggest renaming or splitting the plugin.

Yes, confirming conditions in accordance with GDPR when submitting a contact form is OK. But it should not block the display of the homepage - there are no personal data.

**Comment by sbillard** [comment]
I understand your position. Then for your site you should not use the GDPR required plugin. The operative word here is "**required**". If your site is not collecting personal information there is no need for the plugin. There are other options such as the cookieconsent plugin for less rigorous needs.

You can also enable the plugin but leave the URL empty. With no url, the site will not force the consent but you can still place the `[POLICYBUTTON {string %1}]` macro where you want the consent. Perhaps that should be an option for the contact form.

**Comment by sbillard** [comment]
Actually, I did forget. If you use the gallery option rather than the plugin the consent requirement only applies to the standard forms which collect user data such as the contact, comment, and register user forms. For other places you can use the macro as above or code in a call to `policySubmitButton`.

From the version 1.7 release notes:

> GDPR
Some tools have been added to help sites conform to the General Data Protection Regulation. There is a new general option, Usage policy, which if enabled will force viewers to acknowledge your site usage policy.  A new function, policySubmitButton(), will display a checkbox until the viewer has acknowledged the policy (by checking the box.) The "submit" button replaces this checkbox once the acknowledgement has occurred. 

The acknowledged state is persistent. For a registered user it remains until cleared by the administrator. For anonymous visitors it is retained by a cookie so will persist until the cookie expires. (If gallery sessions is enabled it persists for the visitor's session.)

Standard forms, such as the comment form, which may capture user data, implement this button. There is also a new plugin, GDPR_required, that allows you to redirect first time viewers to your site usage page for confirmation before they can view any other content.

**Comment by Mates-K1** [comment]
I think I am almost-moderate user of NPG, but I am not able to set macros. :/ I looked to user manual, plugin description, but there are only general/universal information. It would be nice to have more detailed manual. Also because of that small things as

> With no url, the site will not force the consent but you can still place the [POLICYBUTTON {string %1}] macro where you want the consent. Perhaps that should be an option for the contact form.

I think it is not clean from plugin description.

And again - how new admin will find plugin to set policy page if that plugins name is GDPR_required?
GDPR is not equal user policy.

And I still would like to have checkbox under contact form - with link to GDPR page, needed to be check before sending.

May I create ticket in NPG forum to continue?

**Comment by sbillard** [comment]
The option is on the general tab and applies to all standard forms that collect user data.
<img width="499" alt="2019-03-12 09_58_35-Dev Admin_ Options-General" src="https://user-images.githubusercontent.com/2474007/54220000-a3398e80-44ad-11e9-88b5-75796d64799e.png">

As to not being clear from the plugin description: 
> A plugin to require that visitors view and acknowledge a site policy page **upon the first visit to your site.**
Please suggest a more clear description.

It is certainly not necessary for you to use macros or other programming if your site does not need special handling, which seems the case.

I understand your desire for more information. Unfortunately that is a general issue.  What documentation there is can be found on the repository and must be augmented by the release notes and plugin documents. I can provide what detail I believe needed, but of course that may fall short for some people. Of course none of this would matter if one does not read the documentation, which is unfortunately typical.

What is really needed is user collaboration on a user manual. I can advise and explain to such a group, but writing it myself as the developer is destined to fall short. I simply know to much to ask the right questions.

Certainly open a discussion on the forum. You can reference this ticket for background. I will close the ticket in anticipation of continuing on the forum.
