### ISSUE TITLE
Did date entry for albums disappear?

### ISSUE THREAD

**Issue by nerdykit** [ZenPhoto20/netPhotoGraphics#977]
I seem to remember that I could set a date (or remove the date) of albums shown in the pictorial grid of available albums.  Now I can't see a place on the album edit page that shows a field for the date.  I prefer to have all of my albums appear "dateless" so now I have one recent album with a date showing and ten more without and I've got no way to change things.  There's a publish and expire date over to the right but that isn't the so-called "album date".  Clearly the information is in the database but I can't see where it might get edited.  Thanks   NK

**Comment by sbillard** [comment]
Yes, the setting of the "date" field was removed. The field has been used internally and gets set for various reasons. The date kind of represents the currency of the album (e.g. for use with things like the daily-summary plugin.) The date field can be only a legitimate date or NULL, and if it is NULL, it will be updated If it is NULL it will be updated from, for instance, the most current image. It also may be updated when a new image is discovered (depending on option settings.) 

What do you mean by making the albums appear "dateless"? Is it just the display on the front-end? You can always just not do a printAlbumDate() function call then. That would seem to me more expedient since otherwise the date will get set on you from time to time and you would have to continuously monitor and reset it.

**Comment by nerdykit** [comment]
Thanks, I'll stop looking for the place to change the date and edit my theme instead.  That will resolve the issue of date display on the album list.  Will close this.
