### ISSUE TITLE
"View ...." button on subalbums and images page

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#978]
Please add "View ..." button to subalbum, images and "all image date" pages too.

Button is on the album page. I usually need to see subalbums or images after any saved changes or due to another reason but this button is only on album pages.

**Comment by sbillard** [comment]
I do not think I understand. There are view buttons on all these pages (maybe not "all image date" since I do not know what page that is.)
<img width="512" alt="Albums-Subalbums" src="https://user-images.githubusercontent.com/2474007/57044929-fc59af00-6c20-11e9-804b-bd9dbae18a6b.png">
<img width="512" alt="Albums-Album" src="https://user-images.githubusercontent.com/2474007/57044945-04195380-6c21-11e9-9e19-796302cb2724.png">
<img width="512" alt="Albums-Images" src="https://user-images.githubusercontent.com/2474007/57044963-0ed3e880-6c21-11e9-9850-2c7aa14dd8d4.png">

**Comment by Mates-K1** [comment]
Img 1 - there is no button to show album "beijing" with all subalbums thumbs
(for example - if I manually sort subalbums (and save it), I cant see them from this page)
Img 2 - it is OK, I know.
Img 3 - there is no button to show album with all images thumbs

**Comment by sbillard** [comment]
Ok, I understand now.
