### ISSUE TITLE
Cant translate branding logo description

### ISSUE THREAD

**Issue by Mates-K1** [ZenPhoto20/netPhotoGraphics#982]
![obrazek](https://user-images.githubusercontent.com/7648991/58246757-31f14400-7d58-11e9-8836-0f9ae23a66b5.png)

There is only first part to translate, it finished by<code>...

![obrazek](https://user-images.githubusercontent.com/7648991/58246870-84326500-7d58-11e9-890d-14e8c295db1d.png)

**Comment by Mates-K1** [comment]
A little bit offtopic: where is branding logo title shown or used?

**Comment by sbillard** [comment]
As the description says, this allows a site to substitute a custom logo for the netPhotoGraphics logo wherever that logo would appear, for instance on the admin pages. Not sure why that description is not translatable, maybe because it has the constant UPLOAD_FOLDER in the string.

Can you try changing the code in admin-tabs/gallery.php to
`								<?php echo sprintf(gettext('A relative link to a logo image (e.g. <code>%1$s/custom_logo.png</code> for an image you have uploaded to your <em>UPLOAD_FOLDER</em> folder.) If this is set, your image will replace the netPhotoGraphics logo. For best results the image should be 78 pixels high.'), UPLOAD_FOLDER); ?>
	` to see if that works?
