### ISSUE TITLE
Add a link to the netphotographics.org forum

### ISSUE THREAD

**Issue by By-oussef** [ZenPhoto20/netPhotoGraphics#991]
Add a link to the netphotographics.org forum in the admin footer.

**Comment by Mates-K1** [comment]
Vote yes, please.
MK


On 20. 6. 2019 at 21:12, <YOUSSEF EL MOURABIT <notifications@github.com>>
wrote:

Add a link to the netphotographics.org forum in the admin footer.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ZenPhoto20/netPhotoGraphics/issues/991?email_source=notifications&email_token=AB2LNX4A3DARR7IJPUGTDS3P3PJBBA5CNFSM4HZ3DSL2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4G2ZD46A>,
or mute the thread

**Comment by By-oussef** [comment]
Great.
